# Generated by Django 4.2.3 on 2023-12-14 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0004_alter_user_options_alter_user_managers_user_bio_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
